package com.indona.invento.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;


@Entity
@Table(name = "new_customer_address")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class NewCustomerAddessEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "is_primary")
    private Boolean Primary;           // TRUE if it's the primary address
    private String branchName;             // First Letter Upper for all words
    private String address;                // Full Address Line
    private String supplierArea;           // First Letter Upper
    private String state;                  // Autogenerated from pincode or manual
    private String country;                // Autogenerated from pincode or manual
    private String pincode;                // Number
    private String mapLocation;           // Link to Map / geo-coordinates

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id")
    @JsonIgnore
    private NewCustomerDetails customer;
}
