package com.indona.invento.entities;

import jakarta.persistence.*;
import lombok.*;

import java.util.List;

@Entity
@Table(name = "unit_master")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class UnitMasterEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String gstRegistrationType;
    private String unitCode;              // Auto-generated (e.g. MEUN0001)
    private String unitName;
    private String unitAddress;
    private String area;

    private String state;                 // Autogenerated via pincode logic
    private String country;
    private String pincode;
    private String mapLocation;

    private String gstOrUin;
    private String gstStateCode;

    private String pan;
    private String isTanAvailable;
    private String tanNumber;
    private String isUdyamAvailable;
    private String udyamNumber;
    private String isIecAvailable;
    private String iecCode;

    private String gstCertificate;
    private String otherDocuments;

    private String typeOfEntity;         // Type of entity

    @OneToMany(mappedBy = "unit", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<UnitContactDetailsEntity> contactDetails;

    private String status;           // Pending / APPROVED / REJECTED (default: Pending)

    @OneToMany(mappedBy = "unit", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<UnitBankDetailsEntity> bankDetails;

    @OneToMany(mappedBy = "unit", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<unitAddressEntity> addressDetails;

}
